const ingredientsArray = [
    "Gin",
    "Creme de Cassis",
    "Fresh Lime Juice",
    "Ginger Beer",
    "Lime",
    "Ginger",
    "Rum",
    "Dark Rum",
    "Banana liqueur",
    "Pineapple Juice",
    "Orange Juice",
    "Sweet and Sour",
    "Demerara Sugar",
    "Cachaca",
    "Vodka",
    "Kahlua",
    "Sugar syrup",
    "Light rum",
    "Grapefruit juice",
    "Bitters",
    "Sugar",
    "Champagne",
    "Orange",
    "Maraschino cherry",
    "Soda Water",
    "Chambord raspberry liqueur",
    "Cherry Brandy",
    "Grenadine",
    "Gin",
    "Sweet and Sour",
    "Carbonated Water",
    "Cherry",
    "Rye Whiskey",
    "Dry Vermouth",
    "Maraschino Cherry",
    "Angostura Bitters",
    "Brandy",
    "Lemon Peel",
    "Sloe Gin",
    "Wine",
    "Sweet Vermouth",
    "Peachtree Schnapps",
    "Surge",
    "Powdered Sugar"
 ]

export const uniqueIngredientsArray = [...new Set(ingredientsArray)]
